begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_table('public','projects','projects exists');
select has_table('public','project_members','project memberships exist');
select has_table('public','project_genres','project genres exist');
select has_table('public','project_tags','project tags exist');
select is((select count(*) from public.licenses),4::bigint,'four licenses seeded');
select is((select count(*) from public.genres),12::bigint,'twelve genres seeded');
select is((select count(*) from public.tags),16::bigint,'sixteen tags seeded');
select is((select count(*) from public.instruments),16::bigint,'sixteen instruments seeded');
select ok((select bool_and(relrowsecurity) from pg_class where oid=any(array['public.licenses'::regclass,'public.genres'::regclass,'public.tags'::regclass,'public.instruments'::regclass,'public.projects'::regclass,'public.project_members'::regclass,'public.project_genres'::regclass,'public.project_tags'::regclass])),'RLS enabled on every exposed table');
select has_function('public','create_project',array['uuid','text','text','numeric','text','smallint','smallint','text','uuid[]','uuid','uuid[]'],'create command exists');
select has_function('public','update_project_metadata',array['uuid','integer','text','text','numeric','text','smallint','smallint','text','uuid[]','uuid','uuid[]'],'update command exists');
select throws_ok($$insert into public.projects(owner_id,create_request_id,title,license_code) values('00000000-0000-0000-0000-000000000001',gen_random_uuid(),'Valid','all-rights-reserved')$$,'23503',null,'unknown owner rejected');
select throws_ok($$insert into public.instruments(id,slug,name,parent_id,sort_order) values('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','self','Self','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',99)$$,'23514',null,'self-parent instrument rejected');
select ok(exists(select 1 from pg_indexes where indexname='project_members_one_owner_idx'),'sole-owner index exists');
select ok(exists(select 1 from pg_indexes where indexname='project_genres_one_primary_idx'),'single-primary index exists');
select is((select count(*) from information_schema.role_table_grants where grantee in ('anon','authenticated') and table_schema='public' and table_name='projects' and privilege_type<>'SELECT'),0::bigint,'projects have no direct application writes');
select is((select count(*) from information_schema.role_table_grants where grantee in ('anon','authenticated') and table_schema='public' and table_name in ('licenses','genres','tags','instruments') and privilege_type<>'SELECT'),0::bigint,'catalogs have no application writes');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname='private' and a.grantee=0 and a.privilege_type='EXECUTE'),0::bigint,'private functions have no PUBLIC execute');
select * from finish(); rollback;
